version: "3.8"

services:
  database:
    image: mongo:7
    container_name: bookstore-db
    volumes:
      - db_data:/data/db
    restart: unless-stopped

  backend:
    image: ghcr.io/duongfesesssss/bookstore-backend:main
    container_name: bookstore-backend
    env_file:
      - ./server/.env
    depends_on:
      - database
    ports:
      - "127.0.0.1:8888:8888"
    restart: unless-stopped

  frontend:
    image: ghcr.io/duongfesesssss/bookstore-frontend:main
    container_name: bookstore-frontend
    env_file:
      - ./client/.env
    depends_on:
      - backend
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped

volumes:
  db_data:
