name: Build & Push images

on:
  push:
    branches: [master]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUXT_PUBLIC_API_BASE: ${{ secrets.NUXT_PUBLIC_API_BASE }}
      NUXT_PUBLIC_BASE_URL: ${{ secrets.NUXT_PUBLIC_BASE_URL }}
      NUXT_PUBLIC_API_PREFIX: ${{ secrets.NUXT_PUBLIC_API_PREFIX }}
      NUXT_PUBLIC_AUTH_BASE: ${{ secrets.NUXT_PUBLIC_AUTH_BASE }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Chuẩn hóa tên image
        id: prep
        env:
          BACKEND_TAG: ghcr.io/${{ github.repository_owner }}/bookstore-backend:main
          FRONTEND_TAG: ghcr.io/${{ github.repository_owner }}/bookstore-frontend:main
        run: |
          echo "backend_tag=${BACKEND_TAG,,}" >> $GITHUB_OUTPUT
          echo "frontend_tag=${FRONTEND_TAG,,}" >> $GITHUB_OUTPUT

      - name: Build & Push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.backend_tag }}

      - name: Build & Push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.frontend_tag }}
          build-args: |
            NUXT_PUBLIC_API_BASE=${{ env.NUXT_PUBLIC_API_BASE }}
            NUXT_PUBLIC_BASE_URL=${{ env.NUXT_PUBLIC_BASE_URL }}
            NUXT_PUBLIC_API_PREFIX=${{ env.NUXT_PUBLIC_API_PREFIX }}
            NUXT_PUBLIC_AUTH_BASE=${{ env.NUXT_PUBLIC_AUTH_BASE }}
